sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

install:
  - mvn -B clean install -Dmaven.test.skip.exec --settings .travis.settings.xml

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  email:
    recipients:
      - david.gautier@ginko.io
